apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-job
  namespace: kube-system
spec:
  schedule: {{ .Values.CleanJob.schedule | quote }}
  suspend: {{ .Values.CleanJob.suspended }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: tiller
          restartPolicy: Never
          imagePullPolicy: Always
          tolerations:
          - key: "type"
            operator: "Equal"
            value: "infrastructure"
            effect: "NoSchedule"
          nodeSelector:
            type: infrastructure
          containers:
          - name: cleanup-job
            image: docker.artifactory.yoox.net/k8s-helper:2
            env:
            - name: CLUSTER_NAME
              value: ((.Env.CLUSTER_NAME))
            args:
            - cleanjob
