---
kind: Service
apiVersion: v1
metadata:
  name: boundary
spec:
  selector:
    app: boudary
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundary
  labels:
    app: boundary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundary
  template:
    metadata:
      labels:
        app: boundary
    spec:
      containers:
      - name: boundary
        image: pluies/hands-on-kubernetes:boundary
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
