---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: visual
spec:
  selector:
    app: visual
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: visual
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: visual
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: visual
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: visual
  labels:
    app: visual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visual
  template:
    metadata:
      labels:
        app: visual
    spec:
      serviceAccountName: visual
      containers:
      - name: visual
        imagePullPolicy: Always
        image: pluies/hands-on-kubernetes:visual
        env:
        - name: "IN_CLUSTER"
          value: "true"
        ports:
        - containerPort: 8080

